import {fail} from './store.mjs';
// Account-owned blobs stay in the backed-up SQLite volume across code updates and pairing changes.
export function jpegSize(bytes){fail(bytes.length>20&&bytes[0]===255&&bytes[1]===216&&bytes.at(-2)===255&&bytes.at(-1)===217,'照片格式不正确');let at=2;while(at+4<bytes.length){fail(bytes[at]===255,'照片格式不正确');while(bytes[at]===255)at++;const marker=bytes[at++];if(marker===217||marker===218)break;const len=bytes.readUInt16BE(at);fail(len>=2&&at+len<=bytes.length,'照片不完整');if([192,193,194].includes(marker)){fail(len>=8,'照片格式不正确');return {width:bytes.readUInt16BE(at+5),height:bytes.readUInt16BE(at+3)}}at+=len}fail(false,'照片格式不正确')}
export function createPhotos(db){db.exec(`CREATE TABLE IF NOT EXISTS account_photos(id TEXT PRIMARY KEY,account INTEGER NOT NULL,created INTEGER NOT NULL,shared INTEGER NOT NULL DEFAULT 0,room INTEGER NOT NULL,image BLOB NOT NULL);CREATE INDEX IF NOT EXISTS photos_owner ON account_photos(account,created);`);
 const metadata=p=>({id:p.id,created:p.created,shared:!!p.shared,room:!!p.room,url:'/api/photos/'+p.id,kind:'daily'});
 return {
 list(account,peer){return db.prepare('SELECT id,account,created,shared,room FROM account_photos WHERE account=? OR (account=? AND shared=1) ORDER BY created DESC,id DESC').all(account,peer??-1).map(p=>({...metadata(p),own:p.account===account}))},
 read(account,peer,id){const p=db.prepare('SELECT * FROM account_photos WHERE id=?').get(id);fail(p&&(p.account===account||(p.account===peer&&p.shared)),'照片不存在',404);return p.image},
 save(account,b){fail(typeof b.id==='string'&&/^[a-f0-9-]{36}$/.test(b.id),'照片编号不正确');const existing=db.prepare('SELECT * FROM account_photos WHERE id=?').get(b.id);if(existing){fail(existing.account===account,'照片编号不可用',409);return metadata(existing)}fail(typeof b.image==='string'&&b.image.startsWith('data:image/jpeg;base64,')&&b.image.length<2200000,'照片太大，请重新拍摄');const bytes=Buffer.from(b.image.slice(23),'base64'),{width,height}=jpegSize(bytes);fail(width>0&&height>0&&width<=1600&&height<=1600,'照片尺寸不正确');fail(db.prepare('SELECT COUNT(*) n FROM account_photos WHERE account=?').get(account).n<200,'相册已满，请先删掉几张照片',409);const created=Date.now();db.prepare('INSERT INTO account_photos(id,account,created,room,image) VALUES(?,?,?,?,?)').run(b.id,account,created,b.room===true?1:0,bytes);return metadata({id:b.id,created,shared:0,room:b.room})},
 change(account,b){fail(['share','delete'].includes(b.action),'照片操作不存在');const p=db.prepare('SELECT * FROM account_photos WHERE id=? AND account=?').get(b.id,account);fail(p,'照片不存在',404);if(b.action==='delete')db.prepare('DELETE FROM account_photos WHERE id=? AND account=?').run(b.id,account);else db.prepare('UPDATE account_photos SET shared=? WHERE id=? AND account=?').run(b.shared===true?1:0,b.id,account);return {ok:true}}
 };
}
