import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createSculptures,sculptureTTL} from '../backend/aurora-sculptures.mjs';
import {createAuroraLodgeService} from '../backend/aurora-lodge.mjs';
import {createPoseBuffer} from '../dist/pose-buffer.js';
function fixture(){const db=new DatabaseSync(':memory:');let t=10000;const sculptures=createSculptures(db,{now:()=>t}),s=createAuroraLodgeService({now:()=>t,sculptures}),u={id:1};s.update(u,{action:'join',room:'outside'});const pose={action:'sync',room:'outside',position:[3,9.6,.1],quaternion:[0,0,0,1],snowPlay:{tool:'ball',ball:[3.5,9.7,.1],radius:.25,rolling:true,base:null}};s.update(u,pose);return {db,s,u,pose,sculptures,advance:n=>t+=n,now:()=>t};}
test('completed sculpture is public, survives restart, expires exactly 72 hours after completion',()=>{const f=fixture();const b={action:'sculpture',id:'snow-test-001',kind:'snowman',x:3.5,z:.1,radius:.25,yaw:.5};f.s.update(f.u,b);const view=f.s.view({id:2});assert.equal(view.sculptures.length,1);assert.equal(view.sculptures[0].expires,f.now()+sculptureTTL);f.s.update(f.u,b);assert.equal(f.s.view(f.u).sculptures.length,1);f.s.update(f.u,{action:'leave'});const restarted=createSculptures(f.db,{now:f.now});assert.equal(restarted.list().length,1);f.advance(sculptureTTL-1);assert.equal(restarted.list().length,1);f.advance(1);assert.equal(restarted.list().length,0);f.db.close();});
test('invalid, distant, overlapping and interior placements are rejected',()=>{const f=fixture(),b={action:'sculpture',id:'duck-test-001',kind:'duck',x:3.5,z:.1,radius:.11};assert.throws(()=>f.s.update(f.u,{...b,x:NaN}));assert.throws(()=>f.s.update(f.u,{...b,x:8}));assert.throws(()=>f.s.update(f.u,{...b,radius:2}));f.s.update(f.u,b);assert.throws(()=>f.s.update(f.u,{...b,id:'duck-test-002'}));f.s.update(f.u,{...f.pose,room:'inside',snowPlay:null});assert.throws(()=>f.s.update(f.u,{...b,id:'duck-test-003',x:3.8}));f.db.close();});
test('unfinished roll and clamp poses synchronize, interpolate and clear on stop',()=>{const f=fixture();const peer=f.s.view({id:2}).guests[0];assert.equal(peer.snowPlay.rolling,true);assert.equal(f.sculptures.list().length,0);const buffer=createPoseBuffer(350);buffer.push(peer,1000,'outside');f.s.update(f.u,{...f.pose,position:[3.2,9.6,.1],snowPlay:{...f.pose.snowPlay,ball:[3.7,9.7,.1],radius:.35}});buffer.push(f.s.view({id:2}).guests[0],1250,'outside');const mid=buffer.sample(1475);assert.ok(Math.abs(mid.position[0]-3.1)<1e-8);assert.ok(Math.abs(mid.snowPlay.radius-.3)<1e-8);assert.ok(Math.abs(mid.snowPlay.ball[0]-3.6)<1e-8);f.s.update(f.u,{...f.pose,snowPlay:null});assert.equal(f.s.view({id:2}).guests[0].snowPlay,null);assert.throws(()=>f.s.update(f.u,{...f.pose,snowPlay:{...f.pose.snowPlay,radius:Infinity}}));f.db.close();});

import {snowPoint} from '../dist/aurora-snow-play.js';
test('sphere grounding preserves lateral coordinates across repeated steps',()=>{let p=snowPoint(3,.5);for(let i=0;i<10000;i++)p=snowPoint(p.x,p.z);assert.equal(p.x,3);assert.equal(p.z,.5);assert.ok(p.y>9&&p.y<10);});

test('placement cannot overlap the tool basket or another outdoor visitor',()=>{const f=fixture(),b={action:'sculpture',id:'safe-test-001',kind:'duck',x:2.9,z:1.25,radius:.11};assert.throws(()=>f.s.update(f.u,b),/设施/);const peer={id:2};f.s.update(peer,{action:'join',room:'outside'});f.s.update(peer,{...f.pose,position:[3.5,9.6,.1],snowPlay:null});assert.throws(()=>f.s.update(f.u,{...b,x:3.5,z:.1}),/有人/);f.db.close();});
import * as T from '../dist/vendor/three.module.js';
import {createSnowPiece} from '../dist/aurora-snow-play.js';
test('snowman and duck geometry is grounded and merged into at most three material draws',()=>{for(const kind of ['snowman','duck']){const world=new T.Group(),root=createSnowPiece(world,{kind,x:3.5,z:.1,radius:kind==='duck'?.11:.3,yaw:1});assert.ok(root.children.length<=3);for(const m of root.children){assert.ok(m.geometry.attributes.position.array.every(Number.isFinite));m.geometry.computeBoundingBox();assert.ok(m.geometry.boundingBox.min.y>=-.001);}assert.equal(root.position.x,3.5);assert.equal(root.position.z,.1);}});

import {snowMotion} from '../dist/aurora-snow-play.js';
test('first-person strafe follows camera right rather than reversing the mobile drag',()=>{for(const yaw of [0,.5,2.35,Math.PI]){const forward=snowMotion(yaw,1,0),right=forward.clone().cross(new T.Vector3(0,1,0)).normalize();assert.ok(snowMotion(yaw,0,1).distanceTo(right)<1e-10);assert.ok(snowMotion(yaw,-1,0).dot(forward)<-.99);}});

import {snowBallLimit,snowBodyLimit} from '../dist/aurora-snow-play.js';
test('rolling has a finite body limit and a proportionate head limit',()=>{assert.equal(snowBodyLimit,.22);assert.equal(snowBallLimit(),.22);assert.equal(snowBallLimit(.22),.22*.63);assert.ok(snowBallLimit(.22)>.08);});
