import test from 'node:test';
import assert from 'node:assert/strict';
import {createCafeChat} from '../backend/cafe-chat.mjs';
import {createAuroraLodgeService} from '../backend/aurora-lodge.mjs';
import {auroraPersona,auroraOrderTool} from '../backend/aurora-host.mjs';
import {auroraMenu} from '../dist/aurora-menu.js';
const env={AI_TEXT_PROVIDER:'tencent',TENCENT_3D_API_KEY:'test-secret',TENCENT_TEXT_MODEL:'hy3'};
const tool=id=>({tool_calls:[{function:{name:'place_cafe_order',arguments:JSON.stringify({items:[id],mode:'here'})}}]});
function fixture(message){let time=10000;const cafe=createAuroraLodgeService({now:()=>time}),u={id:1};cafe.update(u,{action:'join'});const requests=[];const chat=createCafeChat({cafe,env,now:()=>time,persona:auroraPersona,menu:auroraMenu,orderTool:auroraOrderTool,fetcher:async(_,o)=>{requests.push(JSON.parse(o.body));return {ok:true,json:async()=>({choices:[{message}]})}}});return {cafe,u,chat,requests,advance:()=>time+=7000};}
test('ice lodge character/menu and real order lifecycle are separate',async()=>{const f=fixture(tool('aurora_cocoa')),b={command:'ice-order-001',message:'请做一杯暖可可'};const r=await f.chat.send(f.u,b);assert.equal(r.ordered,true);assert.match(f.requests[0].messages[0].content,/凛灯/);assert.ok(!f.requests[0].tools[0].function.parameters.properties.items.items.enum.includes('cafe_latte'));assert.deepEqual(await f.chat.send(f.u,b),r);assert.throws(()=>f.cafe.update(f.u,{action:'take'}));f.advance();f.cafe.update(f.u,{action:'take'});assert.equal(f.cafe.view(f.u).guests[0].held.items[0],'aurora_cocoa');f.cafe.update(f.u,{action:'finish'});assert.equal(f.cafe.view(f.u).guests[0].held,null);assert.deepEqual(f.cafe.view({id:2}).guests,[])});
test('conversation does not order and cafe menu is rejected',async()=>{const f=fixture({content:'要不要坐一会儿？'});assert.equal((await f.chat.send(f.u,{command:'ice-chat-001',message:'今天很累'})).ordered,false);assert.equal(f.cafe.view(f.u).guests[0].order,null);const bad=fixture(tool('cafe_latte'));await assert.rejects(bad.chat.send(bad.u,{command:'ice-invalid-001',message:'来杯拿铁'}));assert.equal(bad.cafe.view(bad.u).guests[0].order,null)});
test('leaving while waiting for AI prevents a late order',async()=>{const f=fixture(null);let resolve;const chat=createCafeChat({cafe:f.cafe,env,persona:auroraPersona,menu:auroraMenu,orderTool:auroraOrderTool,fetcher:()=>new Promise(r=>resolve=r)});const waiting=chat.send(f.u,{command:'ice-late-001',message:'来杯可可'});f.cafe.update(f.u,{action:'leave'});resolve({ok:true,json:async()=>({choices:[{message:tool('aurora_cocoa')}]})});await assert.rejects(waiting);assert.deepEqual(f.cafe.view(f.u).guests,[])});
