import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createCafe} from '../backend/cafe.mjs';
import {cafeMenu,islandSky,cafeSeats,cafeWalkable} from '../dist/cafe-catalog.js';
function setup(){const db=new DatabaseSync(':memory:');let time=Date.parse('2026-10-03T04:00:00Z'),delivered=[];const cafe=createCafe(db,{now:()=>time,partner:u=>u.id<3?({id:u.id===1?2:1}):null,deliver:(u,item,id)=>delivered.push({account:u.id,item:item.id,id})});const user=id=>({id,nickname:'熊'+id,avatar:id%2});return {db,cafe,user,delivered,advance:ms=>time+=ms}}
test('public visitors see strangers but expose no private account records',()=>{const f=setup();try{f.cafe.update(f.user(1),{action:'join'});const r=f.cafe.update(f.user(2),{action:'join'});assert.equal(r.guests.length,2);assert.equal(r.room,1);assert.equal(r.guests[0].space,undefined);assert.equal(r.guests[0].username,undefined);assert.deepEqual(r.sky,f.cafe.view(f.user(1)).sky)}finally{f.db.close()}});
test('seat claims are exclusive, leave and stale connections release them',()=>{const f=setup();try{for(const id of [1,2])f.cafe.update(f.user(id),{action:'join'});f.cafe.update(f.user(1),{action:'seat',seat:'t0-0'});assert.throws(()=>f.cafe.update(f.user(2),{action:'seat',seat:'t0-0'}),/已经有人/);f.cafe.update(f.user(2),{action:'seat',seat:'t0-1'});f.cafe.update(f.user(1),{action:'leave'});assert.doesNotThrow(()=>f.cafe.update(f.user(2),{action:'seat',seat:'t0-0'}));f.advance(21000);assert.equal(f.cafe.has(2),false);assert.equal(f.cafe.update(f.user(3),{action:'join'}).guests.length,1)}finally{f.db.close()}});
test('takeaway is idempotent across retries and service restart',()=>{const f=setup();try{const u=f.user(1),b={action:'order',command:'order-unique-1',item:'cafe_cherry',mode:'takeaway'};f.cafe.update(u,{action:'join'});f.cafe.update(u,b);f.cafe.update(u,b);assert.equal(f.delivered.length,1);const next=createCafe(f.db,{deliver:()=>assert.fail('must not redeliver')});next.update(u,{action:'join'});assert.equal(next.update(u,b).ordered,true);assert.throws(()=>next.update(u,{...b,item:'cafe_latte'}),/编号已使用/)}finally{f.db.close()}});
test('failed delivery rolls back receipt, allows retry and does not grant other users items',()=>{const f=setup();try{let fail=true;const service=createCafe(f.db,{deliver:u=>{assert.equal(u.id,1);if(fail)throw Error('冰箱满了')}}),u=f.user(1),b={action:'order',command:'order-unique-2',item:'cafe_latte',mode:'takeaway'};service.update(u,{action:'join'});assert.throws(()=>service.update(u,b),/冰箱满了/);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM cafe_orders').get().n,0);fail=false;assert.equal(service.update(u,b).ordered,true)}finally{f.db.close()}});
test('dine-in waits for preparation and prevents replacing unconsumed order',()=>{const f=setup();try{const u=f.user(1);f.cafe.update(u,{action:'join'});f.cafe.update(u,{action:'order',command:'dine-in-001',item:'cafe_cupcake',mode:'here'});assert.throws(()=>f.cafe.update(u,{action:'eat'}),/制作中/);f.advance(4000);assert.throws(()=>f.cafe.update(u,{action:'order',command:'dine-in-002',item:'cafe_latte',mode:'here'}),/手里的/);f.cafe.update(u,{action:'eat'});assert.equal(f.cafe.view(u).guests[0].held,null)}finally{f.db.close()}});
test('invalid orders and coordinates cannot enter state; rooms are bounded',()=>{const f=setup();try{for(let i=1;i<=9;i++)f.cafe.update(f.user(i),{action:'join'});assert.equal(f.cafe.view(f.user(1)).guests.length,8);assert.equal(f.cafe.view(f.user(9)).guests.length,1);assert.throws(()=>f.cafe.update(f.user(1),{action:'order',command:'valid-command',item:'fake',mode:'takeaway'}),/菜单/);const r=f.cafe.update(f.user(1),{action:'sync',x:Infinity,z:NaN,yaw:0});assert.ok(Number.isFinite(r.guests[0].x));assert.equal(cafeMenu.filter(i=>i.kind==='dessert').length,6)}finally{f.db.close()}});
test('island day and night follow Beijing time independently of visitor timezone',()=>{assert.equal(islandSky(Date.parse('2026-10-03T04:00:00Z')).hour,12);assert.equal(islandSky(Date.parse('2026-10-03T14:00:00Z')).night,true)});

test('a full partner room is reported instead of silently separating the pair',()=>{const f=setup();try{for(const id of [1,3,4,5,6,7,8,9])f.cafe.update(f.user(id),{action:'join'});assert.throws(()=>f.cafe.update(f.user(2),{action:'join'}),/对方所在.*已满/);f.cafe.update(f.user(3),{action:'leave'});assert.equal(f.cafe.update(f.user(2),{action:'join'}).room,1)}finally{f.db.close()}});

test('expanded curved pavilion keeps seat approaches walkable and excludes sea corners',()=>{
 for(const seat of cafeSeats)assert.equal(cafeWalkable(seat.x,seat.z+.58),true,seat.id);
 assert.equal(cafeWalkable(0,5.8),true);
 assert.equal(cafeWalkable(6.4,4),false);
 assert.equal(cafeWalkable(0,7),false);
});
