import test from 'node:test';
import assert from 'node:assert/strict';
import {createCafeChat} from '../backend/cafe-chat.mjs';
import {cafeSeats,cafeWalkable} from '../dist/cafe-catalog.js';
const env={AI_TEXT_PROVIDER:'tencent',TENCENT_3D_API_KEY:'test-secret',TENCENT_TEXT_MODEL:'hy3'};
test('three bar seats face host and have walkable approaches',()=>{const seats=cafeSeats.filter(s=>s.zone==='bar');assert.equal(seats.length,3);for(const s of seats){assert.equal(s.yaw,Math.PI);assert.ok(cafeWalkable(s.approachX,s.approachZ));assert.ok(s.avatarY>.52)}});
test('chat accepts standing visitors, isolates history and deduplicates successful retries',async()=>{let seat=null,time=10000;const calls=[];const chat=createCafeChat({env,now:()=>time,cafe:{view:u=>({guests:[{id:u.id,seat}]})},fetcher:async(url,options)=>{calls.push(JSON.parse(options.body));assert.equal(url.hostname,'tokenhub.tencentmaas.com');return {ok:true,json:async()=>({choices:[{message:{content:'欢迎来坐坐。'}}]})}}});const u={id:1},b={command:'message-001',message:'今天很开心'};assert.equal((await chat.send(u,b)).reply,'欢迎来坐坐。');await chat.send(u,b);assert.equal(calls.length,1);time+=3000;await chat.send(u,{command:'message-002',message:'你记得我刚才说什么吗'});assert.equal(calls[1].messages.length,4);time+=3000;await chat.send({id:2},b);assert.equal(calls[2].messages.length,2);assert.equal(calls[0].tools[0].function.name,'place_cafe_order');assert.equal(calls[0].model,'hy3');});
test('concurrent sends and provider failures do not expose keys or append failed turns',async()=>{let release,time=10000;const chat=createCafeChat({env,now:()=>time,cafe:{view:u=>({guests:[{id:u.id,seat:'bar-1'}]})},fetcher:()=>new Promise(r=>release=r)});const b={command:'message-001',message:'你好'},waiting=chat.send({id:1},b);await assert.rejects(chat.send({id:1},b),/正在回复/);release({ok:false,status:429});await assert.rejects(waiting,/暂时忙/);time+=3000;const retry=chat.send({id:1},b);release({ok:true,json:async()=>({choices:[{message:{content:'你好'}}]})});assert.equal((await retry).reply,'你好');await assert.rejects(chat.send({id:1},{...b,message:'x'.repeat(601)}),/600/)});

import {DatabaseSync} from 'node:sqlite';
import {createCafe} from '../backend/cafe.mjs';
function orderFixture(response){let time=10000;const db=new DatabaseSync(':memory:'),cafe=createCafe(db,{now:()=>time}),u={id:1,avatar:0,nickname:'客人'};cafe.update(u,{action:'join'});cafe.update(u,{action:'seat',seat:'bar-0'});const chat=createCafeChat({cafe,env,now:()=>time,fetcher:async()=>({ok:true,json:async()=>({choices:[{message:response}]})})});return {db,cafe,u,chat,advance:()=>time+=3000}}
const tool=(items=['cafe_latte','cafe_cupcake'],mode='here')=>({tool_calls:[{function:{name:'place_cafe_order',arguments:JSON.stringify({items,mode})}}]});
test('explicit AI order uses real preparation queue and retries do not duplicate',async()=>{const f=orderFixture(tool());try{const b={command:'chat-order-01',message:'来杯拿铁和纸杯蛋糕，在这里吃'};const r=await f.chat.send(f.u,b);assert.equal(r.ordered,true);const g=f.cafe.view(f.u).guests[0];assert.deepEqual(g.order.items,['cafe_latte','cafe_cupcake']);assert.ok(g.order.readyAt>g.order.startedAt);assert.equal(g.held,null);assert.deepEqual(await f.chat.send(f.u,b),r);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM cafe_orders').get().n,1)}finally{f.db.close()}});
test('chatting/recommendations do not order; invalid menus and extra tools cannot execute',async()=>{for(const response of [{content:'想听你说说今天。'},tool(['not-in-menu']),{tool_calls:[...tool().tool_calls,...tool().tool_calls]}]){const f=orderFixture(response);try{const b={command:'chat-order-02',message:'你喜欢喝什么？'};if(response.content)assert.equal((await f.chat.send(f.u,b)).ordered,false);else await assert.rejects(f.chat.send(f.u,b));assert.equal(f.db.prepare('SELECT COUNT(*) n FROM cafe_orders').get().n,0)}finally{f.db.close()}}});
test('already pending order yields honest reply rather than another preparation',async()=>{const f=orderFixture(tool());try{await f.chat.send(f.u,{command:'first-chat-order',message:'来杯拿铁'});f.advance();const r=await f.chat.send(f.u,{command:'second-chat-order',message:'再来一杯'});assert.equal(r.ordered,false);assert.match(r.reply,/已经在/);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM cafe_orders').get().n,1)}finally{f.db.close()}});
test('leaving cafe during model request prevents late order',async()=>{const f=orderFixture(tool());try{let resolve;const chat=createCafeChat({cafe:f.cafe,env,fetcher:()=>new Promise(r=>resolve=r)});const waiting=chat.send(f.u,{command:'late-chat-order',message:'来一杯拿铁'});f.cafe.update(f.u,{action:'leave'});resolve({ok:true,json:async()=>({choices:[{message:tool()}]})});await assert.rejects(waiting,/已经离开咖啡馆/);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM cafe_orders').get().n,0)}finally{f.db.close()}});

test('chat accepts any seat and rejects absent visitors',async()=>{let present=true;const chat=createCafeChat({env,cafe:{view:u=>({guests:present?[{id:u.id,seat:'t0-0'}]:[]})},fetcher:async()=>({ok:true,json:async()=>({choices:[{message:{content:'慢慢坐。'}}]})})});assert.equal((await chat.send({id:1},{command:'table-chat-001',message:'你好'})).reply,'慢慢坐。');present=false;await assert.rejects(chat.send({id:1},{command:'table-chat-002',message:'你好'}),/先进入/)});
