import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createCafe} from '../backend/cafe.mjs';
import {cafeMenu,islandSky,cafeSeats,cafeWalkable} from '../dist/cafe-catalog.js';
function setup(){const db=new DatabaseSync(':memory:');let time=Date.parse('2026-10-03T04:00:00Z'),delivered=[];const cafe=createCafe(db,{now:()=>time,partner:u=>u.id<3?({id:u.id===1?2:1}):null,deliver:(u,item,id)=>delivered.push({account:u.id,item:item.id,id})});const user=id=>({id,nickname:'熊'+id,avatar:id%2});return {db,cafe,user,delivered,advance:ms=>time+=ms,now:()=>time}}
test('public visitors see strangers but expose no private account records',()=>{const f=setup();try{f.cafe.update(f.user(1),{action:'join'});const r=f.cafe.update(f.user(2),{action:'join'});assert.equal(r.guests.length,2);assert.equal(r.room,1);assert.equal(r.guests[0].space,undefined);assert.equal(r.guests[0].username,undefined);assert.deepEqual(r.sky,f.cafe.view(f.user(1)).sky)}finally{f.db.close()}});
test('seat claims are exclusive, leave and stale connections release them',()=>{const f=setup();try{for(const id of [1,2])f.cafe.update(f.user(id),{action:'join'});f.cafe.update(f.user(1),{action:'seat',seat:'t0-0'});assert.throws(()=>f.cafe.update(f.user(2),{action:'seat',seat:'t0-0'}),/已经有人/);f.cafe.update(f.user(2),{action:'seat',seat:'t0-1'});f.cafe.update(f.user(1),{action:'leave'});assert.doesNotThrow(()=>f.cafe.update(f.user(2),{action:'seat',seat:'t0-0'}));f.advance(21000);assert.equal(f.cafe.has(2),false);assert.equal(f.cafe.update(f.user(3),{action:'join'}).guests.length,1)}finally{f.db.close()}});
test('invalid orders and coordinates cannot enter state; rooms are bounded',()=>{const f=setup();try{for(let i=1;i<=9;i++)f.cafe.update(f.user(i),{action:'join'});assert.equal(f.cafe.view(f.user(1)).guests.length,8);assert.equal(f.cafe.view(f.user(9)).guests.length,1);assert.throws(()=>f.cafe.update(f.user(1),{action:'order',command:'valid-command',item:'fake',mode:'takeaway'}),/菜单/);const r=f.cafe.update(f.user(1),{action:'sync',x:Infinity,z:NaN,yaw:0});assert.ok(Number.isFinite(r.guests[0].x));assert.equal(cafeMenu.filter(i=>i.kind==='dessert').length,6)}finally{f.db.close()}});
test('island day and night follow Beijing time independently of visitor timezone',()=>{assert.equal(islandSky(Date.parse('2026-10-03T04:00:00Z')).hour,12);assert.equal(islandSky(Date.parse('2026-10-03T14:00:00Z')).night,true)});

test('a full partner room is reported instead of silently separating the pair',()=>{const f=setup();try{for(const id of [1,3,4,5,6,7,8,9])f.cafe.update(f.user(id),{action:'join'});assert.throws(()=>f.cafe.update(f.user(2),{action:'join'}),/对方所在.*已满/);f.cafe.update(f.user(3),{action:'leave'});assert.equal(f.cafe.update(f.user(2),{action:'join'}).room,1)}finally{f.db.close()}});

test('expanded curved pavilion keeps seat approaches walkable and excludes sea corners',()=>{
 for(const seat of cafeSeats)assert.equal(cafeWalkable(seat.approachX??seat.x,seat.approachZ??seat.z+.58),true,seat.id);
 assert.equal(cafeWalkable(0,5.8),true);
 assert.equal(cafeWalkable(6.4,4),false);
 assert.equal(cafeWalkable(0,7),false);
});

test('window and terrace seats face the sea and stand back into their aisle',()=>{const f=setup();try{const u=f.user(1);f.cafe.update(u,{action:'join'});for(const id of ['window-1','terrace-1']){const seated=f.cafe.update(u,{action:'seat',seat:id}).guests[0];assert.equal(seated.yaw,cafeSeats.find(s=>s.id===id).yaw);const standing=f.cafe.update(u,{action:'stand'}).guests[0];assert.equal(standing.z,cafeSeats.find(s=>s.id===id).approachZ);assert.ok(cafeWalkable(standing.x,standing.z));}}finally{f.db.close()}});


function counter(f,id=1){const u=f.user(id);f.cafe.update(u,{action:'join'});f.cafe.update(u,{action:'sync',x:.35,z:-1.55,yaw:Math.PI});return u}
const order=(command='order-tray-001',mode='here')=>({action:'order',command,mode,items:['cafe_latte','cafe_cupcake']});
test('order requires presence at the counter and permits drink plus dessert',()=>{const f=setup();try{const u=f.user(1);f.cafe.update(u,{action:'join'});assert.throws(()=>f.cafe.update(u,order()),/先到吧台/);counter(f);const r=f.cafe.update(u,order());assert.equal(r.guests[0].order.items.length,2);assert.equal(r.guests[0].held,null);assert.throws(()=>f.cafe.update(u,order('next-order')),/已经在/)}finally{f.db.close()}});
test('single barista queues requests and retries never restart preparation',()=>{const f=setup();try{const a=counter(f),b=counter(f,2);f.cafe.update(a,order());const first=f.cafe.view(a).guests.find(g=>g.id===1).order;f.cafe.update(a,order());assert.deepEqual(f.cafe.view(b).guests.find(g=>g.id===1).order,first);f.cafe.update(b,order('second-order'));const second=f.cafe.view(b).guests.find(g=>g.id===2).order;assert.ok(second.startedAt>=first.readyAt);assert.equal(f.delivered.length,0)}finally{f.db.close()}});
test('food stays on counter until pickup; collected tray is consumed only while seated',()=>{const f=setup();try{const u=counter(f);f.cafe.update(u,order());assert.throws(()=>f.cafe.update(u,{action:'pickup',command:order().command}),/还在准备/);f.advance(17000);assert.equal(f.cafe.view(u).guests[0].held,null);f.cafe.update(u,{action:'sync',x:3,z:2,yaw:0});assert.throws(()=>f.cafe.update(u,{action:'pickup',command:order().command}),/取餐处/);counter(f);f.cafe.update(u,{action:'pickup',command:order().command});assert.equal(f.cafe.view(u).guests[0].held.pickedAt,f.now());assert.equal(f.cafe.view(u).guests[0].handoff,null);assert.throws(()=>f.cafe.update(u,{action:'eat',item:'cafe_cupcake'}),/座位/);f.cafe.update(u,{action:'seat',seat:'t1-0'});f.cafe.update(u,{action:'eat',item:'cafe_cupcake'});assert.deepEqual(f.cafe.view(u).guests[0].held.items,['cafe_latte']);f.cafe.update(u,{action:'eat',item:'cafe_latte'});assert.equal(f.cafe.view(u).guests[0].held,null)}finally{f.db.close()}});
test('takeaway delivers only on collection and duplicate collection cannot duplicate food',()=>{const f=setup();try{const u=counter(f),b=order('takeaway-001','takeaway');f.cafe.update(u,b);assert.equal(f.delivered.length,0);f.advance(17000);f.cafe.update(u,{action:'pickup',command:b.command});f.cafe.update(u,{action:'pickup',command:b.command});assert.equal(f.delivered.length,2);assert.throws(()=>f.cafe.update(f.user(2),{action:'pickup',command:b.command}));}finally{f.db.close()}});
test('pending orders survive restart but used trays do not return on entry',()=>{const f=setup();try{const u=counter(f);f.cafe.update(u,order());f.cafe.update(u,{action:'leave'});const next=createCafe(f.db,{now:f.now});next.update(u,{action:'join'});assert.equal(next.view(u).guests[0].order.command,order().command);f.advance(17000);next.update(u,{action:'sync',x:.35,z:-1.55,yaw:Math.PI});next.update(u,{action:'pickup',command:order().command});next.update(u,{action:'leave'});const restored=createCafe(f.db,{now:f.now});restored.update(u,{action:'join'});assert.equal(restored.view(u).guests[0].held,null);assert.equal(restored.view(u).guests[0].order,null)}finally{f.db.close()}});
test('failed two-item takeaway rolls back both inventory writes and receipt',()=>{const f=setup();try{f.db.exec('CREATE TABLE inventory(item TEXT)');let failed=true;const c=createCafe(f.db,{now:f.now,deliver:(u,item)=>{f.db.prepare('INSERT INTO inventory VALUES(?)').run(item.id);if(item.id==='cafe_cupcake'&&failed)throw Error('冰箱满了')}}),u=f.user(1),b=order('rollback-001','takeaway');c.update(u,{action:'join'});c.update(u,{action:'sync',x:.35,z:-1.55,yaw:0});c.update(u,b);f.advance(17000);assert.throws(()=>c.update(u,{action:'pickup',command:b.command}),/冰箱/);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM inventory').get().n,0);assert.ok(c.view(u).guests[0].order);failed=false;c.update(u,{action:'pickup',command:b.command});assert.equal(f.db.prepare('SELECT COUNT(*) n FROM inventory').get().n,2)}finally{f.db.close()}});

test('legacy receipts migrate as already collected and cannot redeliver',()=>{const db=new DatabaseSync(':memory:');try{db.exec("CREATE TABLE cafe_orders(account INTEGER NOT NULL,command TEXT NOT NULL,item TEXT NOT NULL,mode TEXT NOT NULL,created INTEGER NOT NULL,PRIMARY KEY(account,command));INSERT INTO cafe_orders VALUES(1,'legacy-001','cafe_latte','takeaway',1)");const cafe=createCafe(db,{deliver:()=>assert.fail('must not deliver legacy order twice')}),u={id:1,avatar:0,username:'bear'};cafe.update(u,{action:'join'});assert.equal(cafe.update(u,{action:'pickup',command:'legacy-001'}).pickedUp,true);assert.equal(db.prepare('SELECT collected FROM cafe_orders').get().collected,1)}finally{db.close()}});

test('ready tray can be collected while host prepares the next order',()=>{const f=setup();try{const a=counter(f),b=counter(f,2);f.cafe.update(a,order('first-ready'));f.cafe.update(b,order('second-cooking'));f.advance(16000);const r=f.cafe.update(a,{action:'pickup',command:'first-ready'});assert.equal(r.pickedUp,true);assert.doesNotThrow(()=>f.cafe.update(a,{action:'seat',seat:'t1-0'}));}finally{f.db.close()}});

test('seated meals progress automatically and standing clears tray immediately',()=>{const f=setup();try{const u=counter(f);f.cafe.update(u,order());f.advance(17000);f.cafe.update(u,{action:'pickup',command:order().command});f.cafe.update(u,{action:'seat',seat:'t0-0'});f.advance(7100);let g=f.cafe.update(u,{action:'sync'}).guests[0];assert.deepEqual(g.held.items,['cafe_cupcake']);f.cafe.update(u,{action:'stand'});assert.equal(f.cafe.view(u).guests[0].held,null);assert.equal(f.cafe.view(u).guests[0].dining,null);f.cafe.update(u,{action:'leave'});assert.equal(f.cafe.update(u,{action:'join'}).guests[0].held,null)}finally{f.db.close()}});
test('complete meal removes the tray without clicks and fresh entry clears stale held items',()=>{const f=setup();try{const u=counter(f);f.cafe.update(u,order());f.advance(17000);f.cafe.update(u,{action:'pickup',command:order().command});f.cafe.update(u,{action:'seat',seat:'bar-0'});f.advance(14100);assert.equal(f.cafe.update(u,{action:'sync'}).guests[0].held,null);f.cafe.update(u,{action:'stand'});counter(f);f.cafe.update(u,order('new-order-002'));f.advance(17000);f.cafe.update(u,{action:'pickup',command:'new-order-002'});assert.equal(f.cafe.update(u,{action:'join',fresh:true}).guests[0].held,null)}finally{f.db.close()}});
