import test from 'node:test';import assert from 'node:assert/strict';import {applyLife,freshLife} from '../dist/life-state.js';
test('home lighting defaults to low, persists per home, permits paired visitors and rejects invalid levels',()=>{const s={worlds:[{life:freshLife()},{life:freshLife()}],bags:[{},{}],events:[]};assert.equal(s.worlds[0].life.nightLight??0,0);for(const level of [0,1,2]){applyLife(s,0,true,{type:'home-light',world:1,level});assert.equal(s.worlds[1].life.nightLight,level);assert.equal(s.worlds[0].life.nightLight??0,0)}assert.equal(s.events.length,0);assert.throws(()=>applyLife(s,0,false,{type:'home-light',world:1,level:1}));for(const level of [-1,3,'1',null])assert.throws(()=>applyLife(s,0,true,{type:'home-light',world:0,level}));});

import * as T from '../dist/vendor/three.module.js';
import {createDesignedHome} from '../dist/designed-home.js';
import {homeLayouts} from '../dist/home-layout.js';
test('night lamps brighten monotonically; computer front points at the brown desk chair',()=>{const root=new T.Group(),home=createDesignedHome(root);home.select(1);home.show(1);home.lighting(true,'night');const levels=[];for(const level of [0,1,2]){home.nightLight(level);home.tick(3);let intensity=0;root.traverse(o=>{if(o.isPointLight)intensity+=o.intensity});levels.push(intensity)}assert(levels[0]<levels[1]&&levels[1]<levels[2]);root.updateMatrixWorld(true);const screen=root.getObjectByName('computer-screen-front');assert(screen);const position=screen.getWorldPosition(new T.Vector3()),normal=new T.Vector3(0,0,1).transformDirection(screen.matrixWorld),seat=new T.Vector3(...homeLayouts[1].upper.seats[0].slice(0,3));assert(normal.dot(seat.sub(position))>0);home.dispose()});

test('every modeled table, floor and wall lamp keeps lighting hit actions after batching',()=>{const root=new T.Group(),home=createDesignedHome(root);let count=0;root.traverse(o=>{if(['room-lamp','wall-lamp'].includes(o.name)){count++;let meshes=0;o.traverse(x=>{if(x.isMesh){meshes++;assert.equal(x.userData.action,'lighting')}});assert.ok(meshes>1)}});assert.ok(count>=10);home.dispose()});
