import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {openStore} from '../backend/store.mjs';
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'echoo-kitchen-'));const filename=path.join(dir,'db.sqlite');let store=openStore(filename);t.after(()=>{try{store.db.close()}catch{}fs.rmSync(dir,{recursive:true,force:true})});return {get store(){return store},reopen(){store.db.close();store=openStore(filename);return store}}}
const act=(s,type,extra={})=>s.life(0,{type,world:0,...extra,revision:s.get(0).revision,command:randomUUID()});
test('cooking is atomic, idempotent, persists as exact cooked recipe and survives reload before choosing',t=>{const x=setup(t),s=x.store,item=randomUUID(),v=s.get(0),milk=v.state.worlds[0].fridge.find(i=>i.food==='milk').qty;const cmd={type:'kitchen-cook',world:0,recipe:'milk',item,revision:v.revision,command:randomUUID()};s.life(0,cmd);s.life(0,cmd);let state=x.reopen().get(0).state;assert.equal(state.worlds[0].fridge.find(i=>i.id===item).food,'cooked_milk');assert.equal(state.worlds[0].fridge.find(i=>i.food==='milk').qty,milk-1);act(x.store,'kitchen-serve',{item});state=x.store.get(0).state;assert.equal(state.worlds[0].meals[0].recipe,'milk');assert(state.events.some(e=>e.id===state.worlds[0].meals[0].event));const snapshot=x.store.get(0);x.store.save(0,{state:snapshot.state,revision:snapshot.revision,command:randomUUID()});act(x.store,'kitchen-eat',{item});assert.equal(x.store.get(0).state.worlds[0].meals.length,0);assert.throws(()=>act(x.store,'kitchen-eat',{item}));});
test('missing ingredients are supplied automatically, including an empty fridge',t=>{const {store:s}=setup(t),row=s.read();row.state.worlds[0].fridge=[];s.db.prepare('UPDATE saves SET state=?').run(JSON.stringify(row.state));const item=randomUUID();act(s,'kitchen-cook',{recipe:'beefnoodles',item});assert.deepEqual(s.get(0).state.worlds[0].fridge,[{id:item,food:'cooked_beefnoodles',qty:1}])});
test('selected raw food is used and unrelated recipes do not consume it',t=>{const {store:s}=setup(t),row=s.read(),source=randomUUID();row.state.worlds[0].fridge=[{id:source,food:'dumplings',qty:1}];s.db.prepare('UPDATE saves SET state=?').run(JSON.stringify(row.state));const before=JSON.stringify(s.read());assert.throws(()=>act(s,'kitchen-cook',{recipe:'milk',item:randomUUID(),source}),/所选食材/);assert.equal(JSON.stringify(s.read()),before);act(s,'kitchen-cook',{recipe:'porkdumplings',item:randomUUID(),source});assert.equal(s.get(0).state.worlds[0].fridge[0].food,'cooked_porkdumplings')});
test('legacy food and flowers migrate once without changing totals on restart',t=>{const x=setup(t),s=x.store,row=s.read();row.state.bags[0]={cookie:7,rose:3};const old=row.state.worlds[0].fridge.filter(i=>i.food==='cookie').reduce((n,i)=>n+i.qty,0);s.db.prepare('UPDATE saves SET state=?').run(JSON.stringify(row.state));s.db.prepare('DELETE FROM settings WHERE key=?').run('unified-storage-v1');let state=x.reopen().get(0).state;assert.deepEqual(state.bags[0],{});assert.equal(state.worlds[0].life.flowers.rose,3);assert.equal(state.worlds[0].fridge.filter(i=>i.food==='cookie').reduce((n,i)=>n+i.qty,0),old+7);const again=x.reopen().get(0).state;assert.deepEqual(again,state)});

test('automatic supply never consumes reserved ingredients and every raw food has a recipe',async t=>{const {recipesForFood,applyKitchen}=await import('../dist/kitchen-state.js'),{foodCatalog}=await import('../dist/food-catalog.js');for(const f of Object.values(foodCatalog).filter(f=>!f.ready))assert(recipesForFood(f.id).length,f.id);const {store:s}=setup(t),state=s.read().state;state.worlds[0].fridge=[{id:'reserved-food',food:'egg',qty:1,event:'gift'}];state.events.push({id:'gift',pending:true,target:1});applyKitchen(state,0,{type:'kitchen-cook',world:0,recipe:'toast',item:randomUUID()},randomUUID);assert.equal(state.worlds[0].fridge[0].qty,1);assert.throws(()=>applyKitchen(state,0,{type:'kitchen-cook',world:0,recipe:'toast',item:randomUUID(),source:'reserved-food'},randomUUID),/留给/)});
