import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {openStore} from '../backend/store.mjs';
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'echoo-life-')),filename=path.join(dir,'save.sqlite'),s=openStore(filename);for(const i of [0,1])s.db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(i,'user'+i,'salt','hash',Date.now());t.after(()=>{try{s.db.close()}catch{}fs.rmSync(dir,{recursive:true,force:true})});return s}
const act=(s,a,b)=>s.life(a,{...b,revision:s.get(a).revision,command:randomUUID()});
function mature(s){const row=s.read();row.state.worlds[0].life.plots.forEach(p=>{if(p)p.readyAt=Date.now()-1});s.db.prepare('UPDATE saves SET state=? WHERE id=1').run(JSON.stringify(row.state))}
function save(s,a,fn){const v=s.get(a);fn(v.state);return s.save(a,{state:v.state,revision:v.revision,command:randomUUID()})}
test('paired visitors plant and harvest, ownership and maturity are enforced',t=>{const s=setup(t);assert.throws(()=>act(s,1,{world:0,type:'plant',plot:0,crop:'rose'}),/配对/);s.accept(1,s.invite(0).code);act(s,1,{world:0,type:'plant',plot:0,crop:'rose'});assert.throws(()=>act(s,0,{world:0,type:'harvest',plot:0}),/成熟/);act(s,0,{world:0,type:'water',plot:0});assert.throws(()=>act(s,1,{world:0,type:'water',plot:0}),/浇过/);mature(s);const revision=s.get(1).revision,cmd={world:0,type:'harvest',plot:0,revision,command:randomUUID()};s.life(1,cmd);s.life(1,cmd);assert.equal(s.get(1).state.bags[1].rose,1);assert.equal(s.get(0).state.bags[1].rose,undefined);assert.throws(()=>s.life(0,{...cmd,command:randomUUID()}),/更新/);assert.throws(()=>act(s,0,{world:0,type:'harvest',plot:0}),/没有可采摘/);act(s,1,{world:0,type:'vase',crop:'rose'});assert.equal(s.get(1).state.bags[1].rose,0);assert.deepEqual(s.get(0).state.worlds[0].life.vase,['rose']);assert.equal(s.get(0).state.events[0].actor,1)});
test('life state cannot be overwritten by ordinary saves; outfits are personal',t=>{const s=setup(t);s.accept(1,s.invite(0).code);assert.throws(()=>save(s,0,x=>x.worlds[0].life.vase.push('rose')),/生活互动/);assert.throws(()=>act(s,1,{world:0,type:'outfit',outfit:'amber'}),/自己/);act(s,0,{world:0,type:'outfit',outfit:'mint'});act(s,1,{world:1,type:'wash',kind:'hands'});act(s,0,{world:1,type:'basket',made:true});assert.equal(s.get(0).state.worlds[1].life.basket.made,1);assert.equal(s.get(0).state.worlds[0].life.outfit,'mint');save(s,0,x=>x.worlds[0].weather='rain');assert.equal(s.get(0).state.worlds[0].life.outfit,'mint');assert.throws(()=>save(s,0,x=>x.worlds[0].fridge.push({id:randomUUID(),food:'rose',qty:1})));});
test('harvested fruit can be gifted to the other fridge and survives restart',t=>{const s=setup(t);s.accept(1,s.invite(0).code);act(s,0,{world:0,type:'plant',plot:1,crop:'strawberry'});mature(s);act(s,0,{world:0,type:'harvest',plot:1});const id=randomUUID();save(s,0,x=>{x.bags[0].strawberry--;x.events.unshift({id,actor:0,world:1,target:1,title:'一颗草莓',body:'花园的收获',kind:'life',shared:true,pending:true,created:Date.now(),weather:'',steps:[],comments:[]});x.worlds[1].fridge.push({id:randomUUID(),food:'strawberry',qty:1,event:id})});const filename=s.db.location();s.db.close();const reopened=openStore(filename);assert.equal(reopened.get(1).state.worlds[1].fridge.find(i=>i.food==='strawberry').qty,1);assert.equal(reopened.get(0).state.worlds[0].life.plots[1],null);reopened.db.close()});
test('old saves gain empty life data without losing inventories',t=>{const s=setup(t),row=s.read(),qty=row.state.worlds[0].fridge[0].qty;row.state.worlds.forEach(w=>delete w.life);s.db.prepare('UPDATE saves SET state=? WHERE id=1').run(JSON.stringify(row.state));assert.equal(s.get(0).state.worlds[0].life.plots.length,6);act(s,0,{world:0,type:'wash',kind:'brush'});assert.equal(s.get(0).state.worlds[0].fridge[0].qty,qty);assert.equal(s.get(0).state.worlds[0].life.wash,1)});
