import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {openStore} from '../backend/store.mjs';import {createMediaService} from '../backend/media.mjs';import {mediaLink} from '../dist/media-state.js';
function setup(t,fetcher){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'echoo-media-')),s=openStore(path.join(dir,'db.sqlite'));for(const i of [0,1])s.db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(i,'user'+i,'salt','hash',Date.now());const m=createMediaService(s,{fetcher});t.after(()=>{s.db.close();fs.rmSync(dir,{recursive:true,force:true})});return {s,m}}
const cmd=(s,m,a,b)=>m.mutate(a,{world:a,...b,revision:s.get(a).revision,command:randomUUID()});
const mockShelf={books:[{bookId:1,title:'秘密书',author:'作者',deepLink:'https://weread.qq.com/web/reader/abc',finishReading:1}],albums:[{albumInfo:{albumId:2,name:'有声故事',authorName:'声音'}}],mp:{title:'文章收藏'}};
test('WeRead binding uses official gateway, imports all shelf types privately and never projects credentials',async t=>{const {s,m}=setup(t,async(url,opt)=>{assert.equal(url,'https://i.weread.qq.com/api/agent/gateway');assert.equal(opt.headers.Authorization,'Bearer wrk-testkey123');assert.deepEqual(JSON.parse(opt.body),{api_name:'/shelf/sync',skill_version:'1.0.4'});return new Response(JSON.stringify(mockShelf))});s.accept(1,s.invite(0).code);const r=await m.sync(0,'wrk-testkey123');assert.equal(r.imported,3);assert.equal(r.items.length,3);assert.equal(m.view(1).items.length,0);assert.equal(JSON.stringify(r).includes('wrk-'),false);assert.equal(r.items[0].finished,true);const b=r.items[0];cmd(s,m,0,{type:'share',kind:'book',id:b.id,shared:true});assert.equal(m.view(1).items.length,1);await m.sync(0);assert.equal(m.view(0).items.length,3);assert.equal(m.view(1).items.length,1);m.disconnect(0);assert.equal(m.view(0).binding.connected,false);assert.equal(m.view(0).items.length,3);await assert.rejects(m.sync(0),/绑定/)});
test('private book and reflections remain private; shared book cannot be edited by visitor',t=>{const {s,m}=setup(t);s.accept(1,s.invite(0).code);cmd(s,m,0,{type:'add',kind:'book',title:'自己的书',author:'某人',url:'',shared:false});const b=m.view(0).items[0];assert.equal(s.get(1).state.events.length,0);assert.throws(()=>cmd(s,m,1,{world:0,type:'note',kind:'book',id:b.id,message:'窥探'}),/不存在/);cmd(s,m,0,{type:'share',kind:'book',id:b.id,shared:true});assert.throws(()=>cmd(s,m,1,{world:0,type:'remove',kind:'book',id:b.id}),/不能/);cmd(s,m,1,{world:0,type:'note',kind:'book',id:b.id,message:'私人感想',shared:false});assert.equal(s.get(0).state.events.some(x=>x.body==='私人感想'),false);cmd(s,m,1,{world:0,type:'note',kind:'book',id:b.id,message:'给你看的感想',shared:true});assert.equal(s.get(0).state.events[0].body,'给你看的感想');s.unlink();assert.equal(m.view(1).items.length,0)});
test('song dedications are persistent, idempotent and recipient-only acknowledgement',t=>{const {s,m}=setup(t);s.accept(1,s.invite(0).code);const b={type:'add',kind:'record',world:1,title:'晴天',url:'https://y.qq.com/n/ryqq/songDetail/abc',message:'今天想起你',revision:s.get(0).revision,command:randomUUID()};m.mutate(0,b);m.mutate(0,b);assert.equal(m.view(1).items.length,1);const id=m.view(1).items[0].id;assert.throws(()=>cmd(s,m,0,{world:1,type:'receive',kind:'record',id}),/自己的/);cmd(s,m,1,{type:'receive',kind:'record',id});assert.equal(m.view(0).items[0].received,true);assert.equal(s.get(0).state.events[0].title,'收下了《晴天》这首留歌');assert.equal(createMediaService(s).view(1).items[0].message,'今天想起你')});
test('failed or outdated WeRead responses keep prior binding and imported data intact',async t=>{let response=mockShelf;const {m}=setup(t,async()=>new Response(JSON.stringify(response)));await m.sync(0,'wrk-testkey123');response={errcode:-1};await assert.rejects(m.sync(0,'wrk-badkey1234'),/失效/);assert.equal(m.view(0).items.length,3);response={...mockShelf,upgrade_info:{message:'upgrade'}};await assert.rejects(m.sync(0),/升级/);assert.equal(m.view(0).binding.connected,true)});
test('disconnect during in-flight sync cannot rebind the key',async t=>{let release;const {m}=setup(t,async()=>{if(release!==false)await new Promise(r=>release=r);return new Response(JSON.stringify(mockShelf))});release=false;await m.sync(0,'wrk-testkey123');release=null;const flight=m.sync(0);m.disconnect(0);release();await assert.rejects(flight,/变更/);assert.equal(m.view(0).binding.connected,false)});
test('links reject scripts, foreign hosts and userinfo; allow official HTTPS and returned WeRead deep links',()=>{for(const x of ['javascript:alert(1)','https://weread.qq.com.evil.com/a','https://user@weread.qq.com/a','http://weread.qq.com/a'])assert.equal(mediaLink(x),'');assert.equal(mediaLink('weread://book/abc','book',true),'weread://book/abc');assert.equal(mediaLink('https://c6.y.qq.com/a','record'),'https://c6.y.qq.com/a')});

test('disconnect cancels a first binding still in flight',async t=>{let release;const {m}=setup(t,async()=>{await new Promise(r=>release=r);return new Response(JSON.stringify(mockShelf))});const flight=m.sync(0,'wrk-testkey123');m.disconnect(0);release();await assert.rejects(flight,/变更/);assert.equal(m.view(0).binding.connected,false);assert.equal(m.view(0).items.length,0)});

test('real book progress preserves percent units and stays private until explicitly shared',async t=>{let percent=1;const {s,m}=setup(t,async(url,opt)=>{const p=JSON.parse(opt.body);if(p.api_name==='/shelf/sync')return new Response(JSON.stringify({...mockShelf,books:[{...mockShelf.books[0],cover:'http://wfqqreader-1252317822.image.myqcloud.com/cover.jpg'}]}));assert.equal(p.bookId,'1');if(p.api_name==='/book/getprogress')return new Response(JSON.stringify({book:{progress:percent,chapterUid:3,updateTime:1750000000}}));if(p.api_name==='/book/chapterinfo')return new Response(JSON.stringify({chapters:[{chapterUid:3,title:'第三章'}]}));throw Error('unexpected API')});s.accept(1,s.invite(0).code);await m.sync(0,'wrk-testkey123');const id=m.view(0).items[0].id;cmd(s,m,0,{type:'share',kind:'book',id,shared:true});await m.progress(0,id);assert.equal(m.view(0).items[0].cover,'https://wfqqreader-1252317822.image.myqcloud.com/cover.jpg');assert.equal(m.view(0).items[0].progress.percent,1);assert.equal(m.view(0).items[0].progress.chapter,'第三章');assert.equal(m.view(0).items[0].finished,false);assert.equal(m.view(1).items[0].progress,undefined);assert.equal(m.view(1).items[0].finished,undefined);await assert.rejects(m.progress(1,id),/电子书/);cmd(s,m,0,{type:'share-progress',kind:'book',id,shared:true});assert.equal(m.view(1).items[0].progress.percent,1);percent=101;await assert.rejects(m.progress(0,id),/有效阅读进度/);assert.equal(m.view(0).items[0].progress.percent,1);cmd(s,m,0,{type:'share-progress',kind:'book',id,shared:false});assert.equal(m.view(1).items[0].progress,undefined);percent=100;await m.progress(0,id);assert.equal(m.view(0).items[0].finished,true)});
test('covers accept official hosts and reject arbitrary URLs',async()=>{const {coverLink}=await import('../dist/media-state.js');assert.equal(coverLink('http://res.weread.qq.com/cover/a.jpg'),'https://res.weread.qq.com/cover/a.jpg');assert.equal(coverLink('https://wx.qpic.cn/a'),'https://wx.qpic.cn/a');assert.equal(coverLink('https://evil.example/a'),'');assert.equal(coverLink('javascript:alert(1)'),'');assert.equal(coverLink('https://qq.com.evil.example/a'),'')});
test('progress finishing after disconnect cannot save new reading data',async t=>{let release;const {m}=setup(t,async(url,opt)=>{const p=JSON.parse(opt.body);if(p.api_name==='/shelf/sync')return new Response(JSON.stringify(mockShelf));if(p.api_name==='/book/chapterinfo')return new Response(JSON.stringify({chapters:[]}));await new Promise(r=>release=r);return new Response(JSON.stringify({book:{progress:33}}))});await m.sync(0,'wrk-testkey123');const id=m.view(0).items[0].id,flight=m.progress(0,id);m.disconnect(0);release();await assert.rejects(flight,/变更/);assert.equal(m.view(0).items[0].progress,undefined)});

test('reading activity enters the journal as a baseline, changes and completion without duplicate records',async t=>{let percent=36,chapterUid=3;const {s,m}=setup(t,async(url,opt)=>{const p=JSON.parse(opt.body);return new Response(JSON.stringify(p.api_name==='/shelf/sync'?mockShelf:p.api_name==='/book/chapterinfo'?{chapters:[{chapterUid:3,title:'晚风'},{chapterUid:4,title:'明天'}]}:{book:{progress:percent,chapterUid,updateTime:1750000000}}))});s.accept(1,s.invite(0).code);await m.sync(0,'wrk-testkey123');const id=m.view(0).items[0].id;
let r=await m.progress(0,id);assert.equal(r.journalAdded,true);assert.match(r.state.events[0].title,/阅读起点/);assert.match(r.state.events[0].body,/已有进度/);assert.match(r.state.events[0].body,/晚风/);assert.equal(s.get(1).state.events.length,0);assert.equal(m.view(0).items[0].readingLog,undefined);
r=await m.progress(0,id);assert.equal(r.journalAdded,false);assert.equal(s.get(0).state.events.length,1);
cmd(s,m,0,{type:'share',kind:'book',id,shared:true});percent=44;r=await m.progress(0,id);assert.match(r.state.events[0].body,/36% 更新到 44%/);assert.equal(s.get(1).state.events.length,0);
cmd(s,m,0,{type:'share-progress',kind:'book',id,shared:true});chapterUid=4;r=await m.progress(0,id);assert.match(r.state.events[0].body,/阅读章节有了变化/);assert.equal(s.get(1).state.events.length,1);
percent=100;r=await m.progress(0,id);assert.match(r.state.events[0].title,/读完/);await m.progress(0,id);assert.equal(s.get(1).state.events.length,2);
cmd(s,m,0,{type:'share-progress',kind:'book',id,shared:false});percent=20;r=await m.progress(0,id);assert.match(r.state.events[0].body,/100% 更新到 20%/);assert.equal(r.state.events[0].shared,false);assert.equal(s.get(1).state.events.length,2);
const v=s.get(0);s.save(0,{state:v.state,revision:v.revision,command:randomUUID()});
});

test('unpaired reflection saves privately and rejected sharing preserves the saved journal',t=>{const {s,m}=setup(t);cmd(s,m,0,{type:'add',kind:'book',title:'自己的书',shared:false});const id=m.view(0).items[0].id;cmd(s,m,0,{type:'note',kind:'book',id,message:'私人读书感想',shared:false});const before=s.get(0);assert.equal(before.state.events[0].body,'私人读书感想');assert.equal(before.state.events[0].shared,false);assert.throws(()=>cmd(s,m,0,{type:'note',kind:'book',id,message:'共同感想',shared:true}),/配对/);assert.deepEqual(s.get(0),before);assert.equal(s.get(1).state.events.length,0);});

test('automatic sync uses recent cached results and does not expose private reading timestamps',async t=>{let calls=0;const {s,m}=setup(t,async(url,opt)=>{calls++;const p=JSON.parse(opt.body);return new Response(JSON.stringify(p.api_name==='/shelf/sync'?{books:[{...mockShelf.books[0],readUpdateTime:1750000000}]}:p.api_name==='/book/getprogress'?{book:{progress:30}}:{chapters:[]}))});s.accept(1,s.invite(0).code);await m.sync(0,'wrk-testkey123');const id=m.view(0).items[0].id;assert.equal(m.view(0).items[0].readUpdateTime,1750000000000);assert.equal((await m.sync(0,undefined,true)).cached,true);assert.equal(calls,1);await m.progress(0,id);const count=calls,revision=s.get(0).revision;assert.equal((await m.progress(0,id,true)).cached,true);assert.equal(calls,count);assert.equal(s.get(0).revision,revision);cmd(s,m,0,{type:'share',kind:'book',id,shared:true});assert.equal(m.view(1).items[0].readUpdateTime,undefined);await m.progress(0,id);assert(calls>count);assert.equal(s.get(0).state.events.length,1);});
