import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {openStore} from '../backend/store.mjs';import {createMusicService} from '../backend/music.mjs';

const song={mid:'003IPDsn4ZWb5H',title:'晚风',singer:[{name:'音乐人'}],album:{mid:'001Mf4Ic1aNYYK'},interval:287};
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'echoo-qq-')),s=openStore(path.join(dir,'db.sqlite'));for(const i of [0,1])s.db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(i,'user'+i,'salt','hash',100+i);let calls=0;const m=createMusicService(s,{fetcher:async url=>{calls++;assert.equal(new URL(url).hostname,'u.y.qq.com');return new Response(JSON.stringify(new URL(url).searchParams.get('data').includes('GetDetail')?{top:{code:0,data:{songInfoList:[{...song,pay:{pay_play:0}}]}}}:{data_id:{data:{tracks:[song]}}}))}});t.after(()=>{s.db.close();fs.rmSync(dir,{recursive:true,force:true})});return {s,m,calls:()=>calls}}
const cmd=(s,m,slot,b)=>m.mutate(slot,{...b,revision:s.get(slot).revision,command:randomUUID()});
test('QQ official metadata needs no key; arbitrary URL fetching rejected',async t=>{const {s,m,calls}=setup(t);const a=await m.list(0);assert.equal(a.configured,true);assert.match(a.tracks[0].cover,/y.gtimg.cn/);assert.equal(a.tracks[0].audio,undefined);await m.list(1);assert.equal(calls(),3);await m.add(0,{link:'https://y.qq.com/n/ryqq/songDetail/'+song.mid});assert.equal(calls(),4);await assert.rejects(m.add(0,{link:'https://evil.test/?songmid='+song.mid}));assert.equal(calls(),4);await assert.rejects(m.track(0,'123'));assert.equal((await m.track(0,'qq:'+song.mid)).track.mid,song.mid)});
test('QQ hearts remain private, gifts require pairing and write journal exactly once',async t=>{const {s,m}=setup(t);await m.list(0);const id='qq:'+song.mid;cmd(s,m,0,{action:'heart',id,liked:true});assert.deepEqual(m.view(1).hearts,[]);assert.deepEqual(createMusicService(s).view(0).hearts,[id]);assert.throws(()=>cmd(s,m,0,{action:'gift',id,message:'给你'}),/配对/);s.accept(1,s.invite(0).code);const b={action:'gift',id,message:'给你',revision:s.get(0).revision,command:randomUUID()};m.mutate(0,b);m.mutate(0,b);assert.equal(m.view(1).gifts.length,1);assert.equal(s.get(1).state.events.length,1);s.unlink();assert.equal(m.view(1).gifts.length,0);});

test('discovery expands an existing one-song library and filters paid tracks',async t=>{const {s}=setup(t);s.db.prepare('INSERT INTO fm_tracks VALUES(?,?,?)').run('qq:'+song.mid,JSON.stringify({...song,id:'qq:'+song.mid,provider:'qq'}),Date.now());let calls=0;const m=createMusicService(s,{fetcher:async()=>{calls++;return new Response(JSON.stringify({top:{code:0,data:{songInfoList:[{...song,mid:'000wM1dr4JszFN',pay:{pay_play:0}},{...song,mid:'004KRGmL0xqW7M',pay:{pay_play:1}}]}}}))}});const r=await m.list(0);assert.equal(r.tracks.length,2);assert(r.tracks.some(t=>t.mid==='000wM1dr4JszFN'));assert(!r.tracks.some(t=>t.mid==='004KRGmL0xqW7M'));await m.list(1);assert.equal(calls,3);});
