import test from 'node:test';import assert from 'node:assert/strict';import {createSocial} from '../backend/social.mjs';import {homeLayouts} from '../dist/home-layout.js';import {createBearContact,routeAroundPeer,BEAR_GAP} from '../dist/bear-contact.js';import {clampZoom} from '../dist/camera-zoom.js';import {recapEvents} from '../dist/recap-data.js';import {applyLife} from '../dist/life-state.js';import * as T from '../dist/vendor/three.module.js';
const u={id:1,slot:0,space:1},p={id:2},pose=x=>({world:0,room:true,floor:0,position:[x,.022,1.5],available:true});
test('social command requires same paired space and proximity, rejects occupied positions and has a bounded broadcast lifetime',()=>{let now=100;const s=createSocial(()=>now),own=pose(-2),peer=pose(-2.95);for(const [partner,a,b]of [[null,own,peer],[p,own,{...peer,world:1}],[p,own,{...peer,floor:1}],[p,own,{...peer,sleeping:true}],[p,own,{...peer,available:false}],[p,own,pose(3)]])assert.throws(()=>s.prepare(u,partner,'highfive',a,b,homeLayouts[0]));const c=s.prepare(u,p,'highfive',own,peer,homeLayouts[0]);assert.ok(Math.abs(new T.Vector3(...c.positions[0]).distanceTo(new T.Vector3(...c.positions[1]))-.84)<.001);s.publish(u,c);assert.equal(s.peek(u).age,0);assert.equal(s.peek({...u,space:2}),null);assert.throws(()=>s.prepare(u,p,'dance',own,peer,homeLayouts[0]));now+=4000;assert.equal(s.peek(u),null)});
test('soft contact separates coincident bears and never pushes through a wall',()=>{const c=createBearContact(),a=new T.Vector3(0,0,0),b=a.clone();const q=c.tick(a,b,true,()=>true,1/60,1);assert.ok(q.distanceTo(b)>=BEAR_GAP);let last=q;for(let i=0;i<120;i++)last=c.tick(last,null,true,()=>true,1/60);assert.ok(last.length()<1.3);c.reset();const blocked=c.tick(a,b,true,()=>false,1/60);assert.deepEqual(blocked.toArray(),a.toArray());const sphere=new T.Vector3(0,4.2,0);assert.ok(Number.isFinite(c.tick(sphere,sphere,false,()=>true,1/60).length()))});
test('zoom can always reverse at either limit; social events appear only in visited owner recap',()=>{assert.equal(clampZoom(99),10);assert.equal(clampZoom(.01),.5);assert.ok(clampZoom(10*.8)<10);assert.ok(clampZoom(.5*1.2)>.5);const events=[{id:'one',actor:1,world:0,shared:true,pending:false,created:100,title:'阿远和小禾击掌'},{id:'two',actor:1,world:0,shared:true,created:101,title:'阿远和小禾一起跳舞'}];assert.deepEqual(recapEvents(events,0,1,200).map(e=>e.kind),['highfive','dance']);assert.equal(recapEvents(events,1,1,200).length,0)});

test('route to sofa clears the partner collision radius instead of getting trapped at a diagonal corner',()=>{const peer={visible:true,sleeping:false,position:[.264,.022,2.514]},from=new T.Vector3(-.485,.022,3.02),path=routeAroundPeer(homeLayouts[0],0,from,1.7,1,peer);assert.ok(path.length);for(const point of path)assert.ok(Math.hypot(point.x-peer.position[0],point.z-peer.position[2])>=BEAR_GAP);assert.ok(path.at(-1).distanceTo(new T.Vector3(1.7,.022,1))<.01)});

import {pairGesture,socialPositions,resetGesture} from '../dist/social-motion.js';
function rig(parent){const avatar=new T.Group(),body=new T.Group();parent.add(avatar);avatar.add(body);const arms=[-1,1].map(x=>{const g=new T.Group();g.position.set(x*.27,.61,0);body.add(g);return g});return {avatar,body,arms,legs:[new T.Group(),new T.Group()]}}
test('paired palms remain in contact throughout a full dance and reset after interruption',()=>{const root=new T.Group();root.rotation.set(.4,.7,.2);const a=rig(root),b=rig(root),anchors=[new T.Vector3(-.42,0,0),new T.Vector3(.42,0,0)];for(const kind of ['highfive','dance'])for(const t of [1,1.5,2,2.3]){const ps=socialPositions(kind,t,anchors,true);a.avatar.position.copy(ps[0]);b.avatar.position.copy(ps[1]);pairGesture(a,b,kind,t,true);for(const i of kind==='dance'?[0,1]:[1])assert.ok(a.arms[i].localToWorld(new T.Vector3(0,-.34,0)).distanceTo(b.arms[1-i].localToWorld(new T.Vector3(0,-.34,0)))<.08);assert.ok(Math.abs(a.avatar.position.distanceTo(b.avatar.position)-.84)<1e-6)}for(const bear of [a,b]){resetGesture(bear);assert.ok(bear.arms.every(g=>g.scale.y===1&&g.rotation.x===0))}const end=socialPositions('dance',4.2,anchors,true);assert.ok(end[0].distanceTo(anchors[0])<1e-6)});
test('collision has a visible bounded rebound, then settles',()=>{const c=createBearContact(),peer=new T.Vector3(),q=c.tick(new T.Vector3(.85,0,0),peer,true,()=>true,1/60);assert.ok(c.bounce>.9);let p=q;for(let i=0;i<60;i++)p=c.tick(p,null,true,()=>true,1/60);assert.ok(p.x-q.x>.12);assert.equal(c.bounce,0);assert.ok(p.x<1.3)});
