import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {createStudio} from '../backend/studio.mjs';
import {createDesignService} from '../backend/design.mjs';
import {studioLayout} from '../dist/studio-layout.js';
import {homeLayouts} from '../dist/home-layout.js';
const sofa={name:'绿抱枕沙发',kind:'sofa',floor:0,x:2.8,z:.95,yaw:-Math.PI/2,width:1.95,height:1,depth:.88,seat:.70,tint:'#ffffff'};
function glb(){let s=JSON.stringify({asset:{version:'2.0'},meshes:[{primitives:[{attributes:{POSITION:0}}]}],accessors:[{count:3}]});s+=' '.repeat((-s.length%4+4)%4);const b=Buffer.alloc(20+s.length);b.writeUInt32LE(0x46546c67);b.writeUInt32LE(2,4);b.writeUInt32LE(b.length,8);b.writeUInt32LE(s.length,12);b.writeUInt32LE(0x4e4f534a,16);b.write(s,20);return b}
function setup(){const db=new DatabaseSync(':memory:');let partner=2,plan={operation:'create',object:sofa,description:'奶油沙发',reply:'预览'},submits=0;const design=createDesignService(db,{partner:()=>({id:partner})});const env={AI_DESIGN_ENABLED:'true',AI_API_KEY:'secret',AI_BASE_URL:'https://llm.example',AI_MODEL:'x',TENCENT_3D_API_KEY:'tencent'};const opts={design,theme:()=>0,partner:id=>partner?{id:id===1?2:id===2?1:0}:null,env,fetcher:async(url,o)=>{if(String(url).includes('chat/completions'))return Response.json({choices:[{message:{tool_calls:[{function:{name:'edit_object',arguments:JSON.stringify(plan)}}]}}]});if(String(url).endsWith('/submit')){submits++;return Response.json({id:'123456'})}if(String(url).endsWith('/query'))return Response.json({status:'completed',data:[{type:'glb',url:'https://test.cos.ap-guangzhou.tencentcos.cn/a.glb'}]});return new Response(glb())}};return {db,design,opts,s:createStudio(db,opts),set:p=>plan=p,unpair:()=>partner=0,submits:()=>submits}}
test('real-generation contract: idempotent task, private asset, preview/save/reload/rollback',async()=>{const t=setup(),b={scope:'home',version:0,prompt:'奶油沙发',requestId:randomUUID()},job=await t.s.start(1,b);assert.deepEqual(await t.s.start(1,b),job);assert.equal(t.submits(),1);await t.s.tick();const p=t.s.get(1,job.job).result;assert.equal(t.design.current(1).design.home.objects,undefined);assert.equal(p.source,'tencent-3d');assert.equal(p.values.objects.length,1);assert.throws(()=>t.s.get(2,job.job));const id=p.values.objects[0].asset;assert.ok(t.s.asset(1,id));assert.ok(t.s.asset(2,id));t.unpair();assert.throws(()=>t.s.asset(2,id));assert.throws(()=>t.s.asset(3,id));t.design.accept(1,{id:p.id,version:0});assert.equal(t.s.list(1).jobs.length,0);assert.equal(t.design.current(1).design.home.objects[0].asset,id);const restarted=createStudio(t.db,t.opts);assert.equal(restarted.get(1,job.job).result.id,p.id);t.design.rollback(1,{version:1,target:0});assert.equal(t.design.current(1).design.home.objects,undefined);t.db.close()});
test('move and continued editing reuse asset, never submit a second 3D task',async()=>{const t=setup(),j=await t.s.start(1,{scope:'home',version:0,prompt:'沙发',requestId:randomUUID()});await t.s.tick();const p=t.s.get(1,j.job).result,o=p.values.objects[0];t.set({operation:'move',target:o.id,object:{...o,width:1.8,tint:'#99aa99'},reply:'调小'});const next=await t.s.start(1,{scope:'home',version:0,draft:p.id,prompt:'小一点',requestId:randomUUID()}),p2=t.s.get(1,next.job).result;assert.equal(p2.values.objects[0].width,1.8);assert.equal(p2.values.objects[0].asset,o.asset);assert.equal(t.submits(),1);t.db.close()});
test('blocks overlapping furniture before submitting any paid task',async()=>{const t=setup();t.set({operation:'create',object:{...sofa,kind:'decor',x:-.35,z:.35,width:1,depth:1},description:'柜子'});await assert.rejects(t.s.start(1,{scope:'home',version:0,prompt:'柜子',requestId:randomUUID()}),/重叠/);assert.equal(t.submits(),0);t.db.close()});
test('tailored garment uses actual language output, independent account and gifted design',async()=>{const t=setup(),tailoring={kind:'dress',name:'蓝色圆点裙',pattern:'dots',color:'#6677aa',accent:'#ffffff',length:.28,flare:.07,pleats:12,patternScale:.05};t.set({operation:'tailor',tailoring,reply:'预览'});const j=await t.s.start(1,{scope:'outfit',version:0,prompt:'蓝色圆点裙',requestId:randomUUID()}),p=t.s.get(1,j.job).result;t.design.accept(1,{id:p.id,version:0});assert.deepEqual(t.design.current(1).design.outfit.tailoring,tailoring);t.design.gift(1,{id:p.id,partnerId:2});const gift=t.design.view(2).gifts[0];assert.equal(gift.label,tailoring.name);t.design.wearGift(2,{id:gift.id,version:0});assert.deepEqual(t.design.current(2).design.outfit.tailoring,tailoring);assert.equal(t.submits(),0);t.db.close()});
test('both original layouts retain routes; invalid furniture never changes originals',()=>{for(const l of homeLayouts){assert.doesNotThrow(()=>studioLayout(l,[],true));const before=JSON.stringify(l);assert.throws(()=>studioLayout(l,[{...sofa,kind:'decor',x:0,z:0,width:8,depth:8}],true));assert.equal(JSON.stringify(l),before)}});

test('new independent furniture moves between floors and can be removed without more generation',async()=>{const t=setup();t.set({operation:'create',object:{...sofa,name:'小灯',kind:'decor',x:-2.5,z:.9,yaw:0,width:.35,height:.8,depth:.35},description:'暖色小灯'});const j=await t.s.start(1,{scope:'home',version:0,prompt:'新增灯',requestId:randomUUID()});await t.s.tick();const p=t.s.get(1,j.job).result,o=p.values.objects[0];assert.equal(o.description,'暖色小灯');t.set({operation:'move',target:o.id,object:{floor:1,x:1,z:1.5}});const j2=await t.s.start(1,{scope:'home',version:0,draft:p.id,prompt:'移到二层',requestId:randomUUID()}),p2=t.s.get(1,j2.job).result;assert.equal(p2.values.objects[0].floor,1);t.set({operation:'remove',target:o.id});const j3=await t.s.start(1,{scope:'home',version:0,draft:p2.id,prompt:'收起来',requestId:randomUUID()});assert.equal(t.s.get(1,j3.job).result.values.objects.length,0);assert.equal(t.submits(),1);t.db.close()});

test('missing clothing arguments are repaired once through language service, not fabricated',async()=>{
 const t=setup(),calls=[],tailoring={kind:'skirt',name:'绿裙',pattern:'plain',color:'#667766',accent:'#ffffff',length:.3,flare:.08,pleats:8,patternScale:.05};
 t.opts.fetcher=async(url,o)=>{const b=JSON.parse(o.body);calls.push(b);return Response.json({choices:[{message:{tool_calls:[{function:{name:'edit_object',arguments:JSON.stringify(calls.length===1?{operation:'tailor',reply:'预览'}:{operation:'tailor',tailoring,reply:'预览'})}}]}}]})};
 const s=createStudio(t.db,t.opts),j=await s.start(1,{scope:'outfit',version:0,prompt:'绿裙',requestId:randomUUID()});
 assert.equal(calls.length,2);assert.deepEqual(s.get(1,j.job).result.values.tailoring,tailoring);assert.equal(t.submits(),0);
 assert.equal(calls[0].model,'hy3');assert.deepEqual(calls[0].thinking,{type:'disabled'});const fn=calls[0].tools[0].function;assert.deepEqual(fn.parameters.properties.operation.enum,['asset_create','asset_regenerate','asset_fit','asset_remove','tailor','style','explain']);assert.ok(fn.parameters.properties.tailoring.required.includes('patternScale'));assert.equal(calls[0].tool_choice.function.name,'edit_object');
 assert.equal(t.design.current(1).version,0);t.db.close();
});

test('unsupported design explains limitation without retry, proposal or paid generation',async()=>{
 const t=setup();let calls=0;
 t.opts.fetcher=async()=>{calls++;return Response.json({choices:[{message:{tool_calls:[{function:{name:'edit_object',arguments:JSON.stringify({operation:'explain',reply:'暂不支持镂空蕾丝，要试试圆点裙吗？'})}}]}}]})};
 const s=createStudio(t.db,t.opts);const j=await s.start(1,{scope:'outfit',version:0,prompt:'蕾丝裙',requestId:randomUUID()});assert.equal(s.get(1,j.job).status,'awaiting_input');assert.match(s.get(1,j.job).reply,/不支持镂空蕾丝/);
 assert.equal(calls,1);assert.equal(t.submits(),0);assert.equal(t.db.prepare('SELECT count(*) n FROM design_proposals').get().n,0);assert.equal(t.design.current(1).version,0);t.db.close();
});

test('repeated incomplete output terminates with a clear error and leaves design untouched',async()=>{
 const t=setup();let calls=0;t.opts.fetcher=async()=>{calls++;return Response.json({choices:[{message:{tool_calls:[{function:{name:'edit_object',arguments:'{"operation":"tailor","tailoring":null}'}}]}}]})};
 const s=createStudio(t.db,t.opts);await assert.rejects(s.start(1,{scope:'outfit',version:0,prompt:'裙子',requestId:randomUUID()}),/设计未完成/);
 assert.equal(calls,2);const diagnostics=t.db.prepare('SELECT data FROM studio_diagnostics').all();assert.equal(diagnostics.length,2);assert.equal(JSON.parse(diagnostics[0].data).reason,'invalid_plan');assert.equal(s.list(1).jobs[0].status,'failed');assert.equal(t.design.current(1).version,0);assert.equal(t.submits(),0);t.db.close();
});

test('natural-language hat styling preserves dress and independently colors accessories',async()=>{const t=setup();t.set({operation:'style',outfit:{hat:'beanie',accessoryColors:{hat:'#b83737'}},reply:'红帽'});const j=await t.s.start(1,{scope:'outfit',version:0,prompt:'红帽子',requestId:randomUUID()}),p=t.s.get(1,j.job).result;assert.equal(p.values.hat,'beanie');assert.equal(p.values.accessoryColors.hat,'#b83737');assert.equal(p.values.garment,'original');t.design.accept(1,{id:p.id,version:0});assert.equal(t.design.current(1).design.outfit.accessoryColors.hat,'#b83737');assert.equal(t.submits(),0);t.db.close()});

const wearable={name:'花瓣草帽',slot:'hat',width:.45,height:.2,depth:.35,x:0,y:.24,z:0,yaw:0,tint:'#ffffff'};
test('free-form accessory uses a real 3D task; fitting reuses asset; saves, gifts and rolls back',async()=>{const t=setup();t.set({operation:'asset_create',wearable,description:'一顶花瓣形草帽，蓝色丝带，帽底敞开，无人物',reply:'预览'});const j=await t.s.start(1,{scope:'outfit',version:0,prompt:'花瓣草帽',requestId:randomUUID()});assert.equal(t.submits(),1);await t.s.tick();const p=t.s.get(1,j.job).result;assert.equal(p.source,'tencent-3d');const o=p.values.wearables[0];assert.ok(t.s.asset(1,o.asset));t.set({operation:'asset_fit',target:o.id,wearable:{y:.22,width:.42},reply:'调低'});const j2=await t.s.start(1,{scope:'outfit',version:0,draft:p.id,prompt:'低一点',requestId:randomUUID()}),p2=t.s.get(1,j2.job).result;assert.equal(p2.values.wearables[0].asset,o.asset);assert.equal(t.submits(),1);t.design.accept(1,{id:p2.id,version:0});t.design.gift(1,{id:p2.id,partnerId:2});t.design.wearGift(2,{id:t.design.view(2).gifts[0].id,version:0});assert.equal(t.design.current(2).design.outfit.wearables[0].asset,o.asset);t.design.rollback(1,{version:1,target:0});assert.equal(t.design.current(1).design.outfit.wearables,undefined);t.db.close()});
test('complex clothing is generated as a concept instead of rejected or substituted',async()=>{const t=setup();t.set({operation:'asset_create',wearable:{...wearable,name:'蕾丝裙',slot:'garment',width:.7,height:.8,depth:.5},description:'蕾丝连衣裙，无人物',reply:'待适配'});const j=await t.s.start(1,{scope:'outfit',version:0,prompt:'蕾丝裙',requestId:randomUUID()});await t.s.tick();const p=t.s.get(1,j.job).result;assert.equal(p.values.wearables[0].slot,'garment');assert.equal(p.values.tailoring,undefined);assert.equal(t.submits(),1);t.design.accept(1,{id:p.id,version:0});assert.equal(t.design.view(1).items[0].name,'蕾丝裙');t.set({operation:'asset_remove',target:p.values.wearables[0].id,reply:'收起'});const remove=await t.s.start(1,{scope:'outfit',version:1,prompt:'收起来',requestId:randomUUID()});assert.equal(t.s.get(1,remove.job).result.values.wearables.length,0);assert.equal(t.submits(),1);t.db.close()});
test('invalid accessory fit is blocked before a paid generation',async()=>{const t=setup();t.set({operation:'asset_create',wearable:{...wearable,width:900},description:'帽子',reply:'预览'});await assert.rejects(t.s.start(1,{scope:'outfit',version:0,prompt:'帽子',requestId:randomUUID()}),/参数/);assert.equal(t.submits(),0);t.db.close()});

test('clarification persists and short reply carries original request, private and version bound',async()=>{const t=setup(),requests=[];let answer={operation:'explain',reply:'先做头纱，还是先做裙子？'};t.opts.fetcher=async(url,o)=>{requests.push(JSON.parse(o.body));return Response.json({choices:[{message:{tool_calls:[{function:{name:'edit_object',arguments:JSON.stringify(answer)}}]}}]})};const s=createStudio(t.db,t.opts),j=await s.start(1,{scope:'outfit',version:0,prompt:'加头纱和蕾丝裙',requestId:randomUUID()});assert.equal(s.get(1,j.job).reply,'先做头纱，还是先做裙子？');assert.equal(t.submits(),0);await assert.rejects(s.start(2,{scope:'outfit',version:0,prompt:'先裙子',replyTo:j.job,requestId:randomUUID()}),/过期/);answer={operation:'style',outfit:{hat:'beanie'},reply:'预览'};const resumed=createStudio(t.db,t.opts);const next=await resumed.start(1,{scope:'outfit',version:0,prompt:'改成针织帽吧',replyTo:j.job,requestId:randomUUID()});const messages=requests.at(-1).messages;assert.equal(messages[1].content,'加头纱和蕾丝裙');assert.equal(messages[2].content,'先做头纱，还是先做裙子？');assert.equal(messages[3].content,'改成针织帽吧');t.design.accept(1,{id:resumed.get(1,next.job).result.id,version:0});assert.ok(!resumed.list(1).jobs.some(x=>x.id===j.job));await assert.rejects(resumed.start(1,{scope:'outfit',version:1,prompt:'好的',replyTo:j.job,requestId:randomUUID()}),/过期/);t.db.close()});

test('malformed tool arguments are supplied to the single text repair with no 3D submission',async()=>{
 const t=setup(),calls=[],bad='{"operation":"explain","reply":"先做头纱",BROKEN}';
 t.opts.fetcher=async(url,o)=>{const b=JSON.parse(o.body);calls.push(b);return Response.json({choices:[{finish_reason:'stop',message:{tool_calls:[{function:{name:'edit_object',arguments:calls.length===1?bad:JSON.stringify({operation:'explain',reply:'先做头纱吗？'})}}]}}]})};
 const s=createStudio(t.db,t.opts),j=await s.start(1,{scope:'outfit',version:0,prompt:'头纱和裙子',requestId:randomUUID()});
 assert.equal(calls.length,2);assert.ok(calls[1].messages.some(m=>m.role==='assistant'&&m.content.includes(bad)));
 assert.equal(s.get(1,j.job).status,'awaiting_input');assert.equal(t.submits(),0);
 const data=JSON.parse(t.db.prepare('SELECT data FROM studio_diagnostics').get().data);
 assert.equal(data.reason,'arguments_json');assert.equal(data.syntax,'invalid_token');assert.ok(!JSON.stringify(data).includes('头纱'));t.db.close();
});
