import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {createStudio} from '../backend/studio.mjs';
import {createDesignService} from '../backend/design.mjs';
import {studioLayout} from '../dist/studio-layout.js';
import {homeLayouts} from '../dist/home-layout.js';
const sofa={name:'绿抱枕沙发',kind:'sofa',floor:0,x:2.8,z:.95,yaw:-Math.PI/2,width:1.95,height:1,depth:.88,seat:.70,tint:'#ffffff'};
function glb(){let s=JSON.stringify({asset:{version:'2.0'},meshes:[{primitives:[{attributes:{POSITION:0}}]}],accessors:[{count:3}]});s+=' '.repeat((-s.length%4+4)%4);const b=Buffer.alloc(20+s.length);b.writeUInt32LE(0x46546c67);b.writeUInt32LE(2,4);b.writeUInt32LE(b.length,8);b.writeUInt32LE(s.length,12);b.writeUInt32LE(0x4e4f534a,16);b.write(s,20);return b}
function setup(){const db=new DatabaseSync(':memory:');let partner=2,plan={operation:'create',object:sofa,description:'奶油沙发',reply:'预览'},submits=0;const design=createDesignService(db,{partner:()=>({id:partner})});const env={AI_DESIGN_ENABLED:'true',AI_API_KEY:'secret',AI_BASE_URL:'https://llm.example',AI_MODEL:'x',TENCENT_3D_API_KEY:'tencent'};const opts={design,theme:()=>0,partner:id=>partner?{id:id===1?2:id===2?1:0}:null,env,fetcher:async(url,o)=>{if(String(url).includes('chat/completions'))return Response.json({choices:[{message:{tool_calls:[{function:{name:'edit_object',arguments:JSON.stringify(plan)}}]}}]});if(String(url).endsWith('/submit')){submits++;return Response.json({id:'123456'})}if(String(url).endsWith('/query'))return Response.json({status:'completed',data:[{type:'glb',url:'https://test.cos.ap-guangzhou.tencentcos.cn/a.glb'}]});return new Response(glb())}};return {db,design,opts,s:createStudio(db,opts),set:p=>plan=p,unpair:()=>partner=0,submits:()=>submits}}
test('real-generation contract: idempotent task, private asset, preview/save/reload/rollback',async()=>{const t=setup(),b={scope:'home',version:0,prompt:'奶油沙发',requestId:randomUUID()},job=await t.s.start(1,b);assert.deepEqual(await t.s.start(1,b),job);assert.equal(t.submits(),1);await t.s.tick();const p=t.s.get(1,job.job).result;assert.equal(t.design.current(1).design.home.objects,undefined);assert.equal(p.source,'tencent-3d');assert.equal(p.values.objects.length,1);assert.throws(()=>t.s.get(2,job.job));const id=p.values.objects[0].asset;assert.ok(t.s.asset(1,id));assert.ok(t.s.asset(2,id));t.unpair();assert.throws(()=>t.s.asset(2,id));assert.throws(()=>t.s.asset(3,id));t.design.accept(1,{id:p.id,version:0});assert.equal(t.s.list(1).jobs.length,0);assert.equal(t.design.current(1).design.home.objects[0].asset,id);const restarted=createStudio(t.db,t.opts);assert.equal(restarted.get(1,job.job).result.id,p.id);t.design.rollback(1,{version:1,target:0});assert.equal(t.design.current(1).design.home.objects,undefined);t.db.close()});
test('move and continued editing reuse asset, never submit a second 3D task',async()=>{const t=setup(),j=await t.s.start(1,{scope:'home',version:0,prompt:'沙发',requestId:randomUUID()});await t.s.tick();const p=t.s.get(1,j.job).result,o=p.values.objects[0];t.set({operation:'move',target:o.id,object:{...o,width:1.8,tint:'#99aa99'},reply:'调小'});const next=await t.s.start(1,{scope:'home',version:0,draft:p.id,prompt:'小一点',requestId:randomUUID()}),p2=t.s.get(1,next.job).result;assert.equal(p2.values.objects[0].width,1.8);assert.equal(p2.values.objects[0].asset,o.asset);assert.equal(t.submits(),1);t.db.close()});
test('blocks overlapping furniture before submitting any paid task',async()=>{const t=setup();t.set({operation:'create',object:{...sofa,kind:'decor',x:-.35,z:.35,width:1,depth:1},description:'柜子'});await assert.rejects(t.s.start(1,{scope:'home',version:0,prompt:'柜子',requestId:randomUUID()}),/重叠/);assert.equal(t.submits(),0);t.db.close()});
test('tailored garment uses actual language output, independent account and gifted design',async()=>{const t=setup(),tailoring={kind:'dress',name:'蓝色圆点裙',pattern:'dots',color:'#6677aa',accent:'#ffffff',length:.28,flare:.07,pleats:12,patternScale:.05};t.set({operation:'tailor',tailoring,reply:'预览'});const j=await t.s.start(1,{scope:'outfit',version:0,prompt:'蓝色圆点裙',requestId:randomUUID()}),p=t.s.get(1,j.job).result;t.design.accept(1,{id:p.id,version:0});assert.deepEqual(t.design.current(1).design.outfit.tailoring,tailoring);t.design.gift(1,{id:p.id,partnerId:2});const gift=t.design.view(2).gifts[0];assert.equal(gift.label,tailoring.name);t.design.wearGift(2,{id:gift.id,version:0});assert.deepEqual(t.design.current(2).design.outfit.tailoring,tailoring);assert.equal(t.submits(),0);t.db.close()});
test('both original layouts retain routes; invalid furniture never changes originals',()=>{for(const l of homeLayouts){assert.doesNotThrow(()=>studioLayout(l,[],true));const before=JSON.stringify(l);assert.throws(()=>studioLayout(l,[{...sofa,kind:'decor',x:0,z:0,width:8,depth:8}],true));assert.equal(JSON.stringify(l),before)}});

test('new independent furniture moves between floors and can be removed without more generation',async()=>{const t=setup();t.set({operation:'create',object:{...sofa,name:'小灯',kind:'decor',x:-2.5,z:.9,yaw:0,width:.35,height:.8,depth:.35},description:'暖色小灯'});const j=await t.s.start(1,{scope:'home',version:0,prompt:'新增灯',requestId:randomUUID()});await t.s.tick();const p=t.s.get(1,j.job).result,o=p.values.objects[0];assert.equal(o.description,'暖色小灯');t.set({operation:'move',target:o.id,object:{floor:1,x:1,z:1.5}});const j2=await t.s.start(1,{scope:'home',version:0,draft:p.id,prompt:'移到二层',requestId:randomUUID()}),p2=t.s.get(1,j2.job).result;assert.equal(p2.values.objects[0].floor,1);t.set({operation:'remove',target:o.id});const j3=await t.s.start(1,{scope:'home',version:0,draft:p2.id,prompt:'收起来',requestId:randomUUID()});assert.equal(t.s.get(1,j3.job).result.values.objects.length,0);assert.equal(t.submits(),1);t.db.close()});
